# Generated by Django 3.2.23 on 2023-12-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=35)),
                ('Price', models.CharField(max_length=25)),
                ('Quantity', models.CharField(max_length=25)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
    ]
