# Generated by Django 3.2.23 on 2023-12-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
