# Generated by Django 3.2.23 on 2023-12-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=25)),
                ('Quantity', models.CharField(max_length=25)),
                ('is_delivered', models.IntegerField(default=0)),
            ],
        ),
    ]
